export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
